import React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { AppProviders } from "@/providers"
import { Modals } from "@/components"
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico"
    }
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AppProviders>
                    <div
                        className="max-w-6xl mx-auto py-10 px-4 space-y-6" //
                    >
                        {children}
                    </div>
                    <Modals />
                    <Toaster position="top-right" reverseOrder={false} />
                </AppProviders>
            </body>
        </html>
    )
}
